### ISSUE TITLE
Demos for milestones

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/peppol-php#135]
For milestone 3:
* [ ] Basic Java to PHP sending demo, invoice gets saved to Nextcloud
* [ ] SMP publisher
* [ ] AS4 compliance
* [ ] addressbook with self-hosted non-Peppol identities
* [ ] option to accept only SMP-identified senders or also self-hosted ID's

For milestone 2:
* [ ] Basic PHP to Java sending demo, select invoice from Nextcloud and recipient from Addressbook
* [ ] SMP lookup (search?)
* [ ] AS4 compliance
* [ ] option to allow only sending to SMP-identified senders or also to self-hosted ID's

For milestone 4:
* [ ] PHP -> gateway -> Java: in sender, configure the gateway; whitelist sender in gateway
* [ ] configure receiver to trust gateway for SMP publishing; configure gateway to trust receiver; resign and publish SMP
